services:
    postgres:
        image: postgres:18
        container_name: rhr-mcp-postgres
        restart: always
        environment:
            TZ: UTC
            POSTGRES_DB: rhr
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5433:5432'
        volumes:
            - rhr_postgres_data:/var/lib/postgresql

volumes:
    rhr_postgres_data:
        name: rhr_postgres_data
